# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0cinference.v1\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xae\x01\n\x0fGenerateRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\'\n\x08messages\x18\x02 \x03(\x0b\x32\x15.inference.v1.Message\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\r\n\x05top_p\x18\x06 \x01(\x02\x12\x0c\n\x04stop\x18\x07 \x03(\t\x12\r\n\x05top_k\x18\x08 \x01(\x05\"\x88\x01\n\rGenerateChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\x15\n\rfinish_reason\x18\x03 \x01(\t\x12\x15\n\rprompt_tokens\x18\x04 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x05 \x01(\x05\x12\x12\n\nrequest_id\x18\x06 \x01(\t\"\x13\n\x11ListModelsRequest\"$\n\x12ListModelsResponse\x12\x0e\n\x06models\x18\x01 \x03(\t2\xad\x01\n\x10InferenceService\x12H\n\x08Generate\x12\x1d.inference.v1.GenerateRequest\x1a\x1b.inference.v1.GenerateChunk0\x01\x12O\n\nListModels\x12\x1f.inference.v1.ListModelsRequest\x1a .inference.v1.ListModelsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=33
  _globals['_MESSAGE']._serialized_end=73
  _globals['_GENERATEREQUEST']._serialized_start=76
  _globals['_GENERATEREQUEST']._serialized_end=250
  _globals['_GENERATECHUNK']._serialized_start=253
  _globals['_GENERATECHUNK']._serialized_end=389
  _globals['_LISTMODELSREQUEST']._serialized_start=391
  _globals['_LISTMODELSREQUEST']._serialized_end=410
  _globals['_LISTMODELSRESPONSE']._serialized_start=412
  _globals['_LISTMODELSRESPONSE']._serialized_end=448
  _globals['_INFERENCESERVICE']._serialized_start=451
  _globals['_INFERENCESERVICE']._serialized_end=624
# @@protoc_insertion_point(module_scope)
